name: 'crypto_dbt'
version: '1.0.0'
config-version: 2

profile: 'crypto_dbt'

model-paths: ["models"]

target-path: "target"   
clean-targets: ["target", "dbt_packages"]

models:
  crypto_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  project: "basic-radius-451516-m7"
