name: Run dbt models on schedule

on:
  workflow_dispatch:        # Allow manual trigger
  schedule:
    - cron: "0 7 * * *"     # Run daily at 7AM UTC

jobs:
  run_dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dbt-bigquery
        run: |
          pip install dbt-bigquery

      - name: Run dbt models
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/keyfile.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/keyfile.json
          dbt deps
          dbt seed --profiles-dir .
          dbt run --profiles-dir .
          dbt test --profiles-dir .